export const alertStyles = {
  info: {
    padding: '12px 16px',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    background: '#e6f4fa',
    color: '#2176ae',
    border: '1px solid #b6e0fe',
    marginBottom: '16px',
    fontSize: '1rem',
    gap: '8px',
  },
  warning: {
    padding: '12px 16px',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    background: '#fff4e5',
    color: '#a15c00',
    border: '1px solid #ffd699',
    marginBottom: '16px',
    fontSize: '1rem',
    gap: '8px',
  },
  success: {
    padding: '12px 16px',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    background: '#e6faea',
    color: '#217e3a',
    border: '1px solid #b6fecb',
    marginBottom: '16px',
    fontSize: '1rem',
    gap: '8px',
  },
};